#!/usr/bin/env bash

# Check if Homebrew is installed
if ! command -v brew &> /dev/null; then
    echo "Homebrew is not installed. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Check if Git is installed
if ! command -v git &> /dev/null; then
    echo "Git is not installed. Installing Git..."
    brew install git
fi

# Create personal directory if it doesn't exist
if [ ! -d "$HOME/personal" ]; then
    mkdir -p "$HOME/personal"
fi

# Clone the repository
git clone https://github.com/khulnasoft/dev "$HOME/personal/dev"

# Run the application
pushd "$HOME/personal/dev"
./run
popd

